### ISSUE TITLE
Blue Spheres crashes after touching a red sphere (Sonic Mania)

### ISSUE THREAD

**Issue by EnterTheVoid-x86** [RSDKModding/Sonic-Mania-Decompilation#261] opened 2024-01-04 13:50 UTC
This is the last text the log.txt had saved before the crash:

`=========================
E:\Github\RSDKv5-Decompilation\RSDKv5\RSDK\User\Dummy\DummyPresence.cpp: SetPresence() # Set Steam rich presence string to Navigating Menu

ManiaModeMenu_Initialize()
ManiaModeMenu_Initialize()
ManiaModeMenu_Initialize()
Save Select
Loaded File Data/Music/SaveSelect.ogg
Attempting to save user file: Achievements.bin
`

**Comment by Mefiresu** [comment] 2024-01-04 14:37
Can you give more information?
Platform, graphics backend (DX9/DX11/GL), whether it was built from source or not, if it happens everytime...

**Comment by EnterTheVoid-x86** [comment] 2024-01-04 17:37
> Can you give more information? Platform, graphics backend (DX9/DX11/GL), whether it was built from source or not, if it happens everytime...

Hi, sorry for not including these originally lol

I'm on Windows 11 23H2, playing on the 64-bit compiled version from github releases with your RSDKv5 decomp aswell, playing on DX11 i think, and it doesn't happen everytime on a new save, this happened on a blue spheres level in Chemical Plant Zone act 2, so I will try to get to that point and see if it happens again.

**Comment by MegAmi24** [comment] 2024-01-04 20:33
Try building the current source code of both the RSDKv5(U) and Mania decomps and seeing if the crash still occurs.

**Comment by Mefiresu** [comment] 2024-07-29 16:34
Closing, can't reproduce crash. Most likely caused by the outdated 1.0.0 build.

**Closed by Mefiresu** 2024-07-29 16:34 UTC
